#!/bin/bash

notebook=$(jq -r .notebook config.json)

ls $notebook

mkdir -p html
singularity exec -e docker://jupyter/datascience-notebook jupyter nbconvert \
    --to html \
    --template classic \
    --output-dir=html \
    --output=index.html \
    $notebook

#--template basic \ #basic is too plain

#create a current snapshot(copy) of the whole notebook to be archived
mkdir -p notebook
rsync -av --exclude "**/input" --exclude "**/.*" $(dirname $notebook)/ notebook/notebook/

#there are things we don't want ..
#ln -sf $(dirname $notebook) notebook


